apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
  namespace: demo-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-demo
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      containers:
      - name: flask-demo
        image: docker.io/<your-dockerhub-username>/flask-demo:latest
        ports:
        - containerPort: 5000

