apiVersion: v1
kind: Service
metadata:
  name: flask-demo
  namespace: demo-cicd
spec:
  type: NodePort
  selector:
    app: flask-demo
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080

